FROM ubuntu:18.04

RUN apt-get -qq update \
 && apt-get -qq install locales wget unzip git python3-pip \
 && rm -rf /var/lib/apt/lists/* \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && locale-gen en_US.UTF-8

ENV LC_ALL en_US.UTF-8

COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

WORKDIR app

COPY bert ./bert

COPY scripts ./scripts

COPY common.py ./
COPY config.py ./
COPY conlleval.py ./
COPY ner.py ./